#port
server:
  port: 9000

#mysql
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/money_mind
    username: root
    password: root

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create  # DDL 생성 전략 설정 (create, update, validate, none)
    show-sql: true      # SQL 쿼리 출력 여부
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
        use_sql_comments: true  # SQL 쿼리에 주석 추가
  security:
    oauth2:
      client:
        registration:
          naver:
            client-id: iOr0e1Kpb_HkDtfYNbxp
            client-secret: ZcfM3__N3J
            scope:
              - name
              - email
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:9000/oauth2/callback/naver
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response


#log
logging.level.org.hibernate.sql: debug

#OAuth2

#JWT Token
jwt:
  secretKey: a612de8bf4c12619ec94fba0a464290b3293fcb8064feeec01fa0db98fd26d3bed17a54abc08e31254a2c16b5287937624f5381ca8b529f484474371ceba2ec8
  expiration: 3600000



