#port
server:
  port: 9000

#mysql
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/money_mind
    username: root
    password: root

  #JPA 설정
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
        use_sql_comments: true
        ddl-auto: create
#        show_sql: true

#log
logging.level.org.hibernate.sql: debug