#port
server:
  port: 9000

#mysql
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/money_mind
    username: root
    password: root

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create  # DDL 생성 전략 설정 (create, update, validate, none)
    show-sql: true      # SQL 쿼리 출력 여부
    properties:
      hibernate:
        format_sql: true  # SQL 쿼리 포맷팅
        use_sql_comments: true  # SQL 쿼리에 주석 추가

#log
logging.level.org.hibernate.sql: debug